# Generated by Django 4.1 on 2022-08-22 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_alter_blog_owmer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blog",
            old_name="owmer",
            new_name="owner",
        ),
    ]
