# Generated by Django 4.1 on 2022-08-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_rename_owmer_blog_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="category",
            field=models.CharField(
                choices=[(1, "Livestyle"), (2, "Trading"), (3, "Programming")],
                default=1,
                max_length=10,
            ),
            preserve_default=False,
        ),
    ]
